# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'swift_boilerplate' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swift_boilerplate
  pod 'Alamofire', '~> 3.4.2'

end
